version: '3.8'

x-common-env: &common-env
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  SPRING_PROFILES_ACTIVE: docker

x-db-env: &db-env
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

x-jwt-env-values: &jwt-env-values
  JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  JWT_EXPIRATION: 86400000
  JWT_REFRESH_TOKEN_EXPIRATION: 604800000

x-rabbitmq-env: &rabbitmq-env
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: 5672
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest

services:
  mysql:
    image: mysql:8.0
    container_name: intellimart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intelimart_auth_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - intellimart-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    build:
      context: ./rabbitmq-docker
      dockerfile: Dockerfile
      args:
        ERLANG_COOKIE: "SUPERSECRETRABBITMQCOOKIE"
    container_name: intellimart-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - intellimart-network
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: intellimart-eureka-server
    ports:
      - "8761:8761"
    environment:
      <<: *common-env
    networks:
      - intellimart-network
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8761/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: intellimart-auth-service
    ports:
      - "8089:8089"
    environment:
      <<: [*common-env, *db-env, *jwt-env-values]
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/intelimart_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    networks:
      - intellimart-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: intellimart-product-service
    ports:
      - "8082:8082"
    environment:
      <<: [*common-env, *db-env]
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/intelimart_product_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      PRODUCT_IMAGES_UPLOAD_DIR: /app/uploads
    volumes:
      - ./product-service/uploads:/app/uploads
    networks:
      - intellimart-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  shopping-cart-service:
    build:
      context: ./shopping-cart-service
      dockerfile: Dockerfile
    container_name: intellimart-shopping-cart-service
    ports:
      - "8083:8083"
    environment:
      <<: [*common-env, *db-env]
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/intelimart_cart_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    networks:
      - intellimart-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: intellimart-order-service
    ports:
      - "8084:8084"
    environment:
      <<: [*common-env, *db-env, *rabbitmq-env]
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/intelimart_order_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      RAZORPAY_KEY_ID: rzp_test_BRg0a8xA7ICk6v
      RAZORPAY_KEY_SECRET: WNfupjGp18ruBLcWkRMQmP3w
      RAZORPAY_WEBHOOK_SECRET: gG1sN0l3c2x4Y1l5d0h0c1F2YjVqN0t2ZzFjMjY0d0Q=
    networks:
      - intellimart-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: intellimart-notification-service
    ports:
      - "8085:8085"
    environment:
      <<: [*common-env, *rabbitmq-env]
    networks:
      - intellimart-network
    depends_on:
      eureka-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      order-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: intellimart-api-gateway
    ports:
      - "8081:8081"
    environment:
      <<: [*common-env, *jwt-env-values]
    networks:
      - intellimart-network
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      shopping-cart-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:
  rabbitmq_data_volume:

networks:
  intellimart-network:
    driver: bridge
